Repository antvis/L7Plot, pull requests merged in 2022-07, with the labels that each got.

#175 chore: layer source
  packages/composite-layers/src/composite-layers/bubble-layer/constants.ts
  packages/composite-layers/src/composite-layers/bubble-layer/index.ts
  packages/composite-layers/src/composite-layers/bubble-layer/types.ts
  packages/composite-layers/src/composite-layers/choropleth-layer/constants.ts
  packages/composite-layers/src/composite-layers/choropleth-layer/index.ts
  packages/composite-layers/src/composite-layers/choropleth-layer/types.ts
  packages/composite-layers/src/composite-layers/common/constants.ts
  packages/composite-layers/src/composite-layers/common/label-layer.ts
  packages/composite-layers/src/composite-layers/common/types.ts
  packages/composite-layers/src/composite-layers/icon-layer/adaptor.ts
  packages/composite-layers/src/composite-layers/icon-layer/constants.ts
  packages/composite-layers/src/composite-layers/icon-layer/icon-font.ts
  packages/composite-layers/src/composite-layers/icon-layer/icon-image.ts
  packages/composite-layers/src/composite-layers/icon-layer/icon.ts
  packages/composite-layers/src/composite-layers/icon-layer/index.ts
  packages/composite-layers/src/composite-layers/icon-layer/types.ts
  packages/composite-layers/src/core/composite-layer.ts
  packages/composite-layers/src/core/constants.ts
  packages/composite-layers/src/index.ts
  packages/composite-layers/src/types/category.ts
  storybook/stories/composite-layers/icon-layer/IconFont.tsx
  storybook/stories/composite-layers/icon-layer/iconImage.tsx
  storybook/stories/composite-layers/icon-layer/index.stories.tsx
Labels: ignore-for-release

#194 feat: 地理数据支持自定义请求
  packages/l7plot/src/plots/choropleth/index.ts
  packages/l7plot/src/plots/choropleth/types.ts
Labels: feature

#196 docs: 文档新增自定义获取数据 API
  packages/l7plot/src/plots/choropleth/index.ts
  packages/l7plot/src/plots/choropleth/types.ts
  website/docs/api/plots/choropleth.zh.md
Labels: documentation
