Repository antvis/L7Plot, pull requests merged in 2022-09, with the labels that each got.

#216 docs: 下线行政区域图 Demo
  website/examples/area/division/demo/europe-pop-est.ts
  website/examples/area/division/demo/meta.json
  website/examples/area/division/demo/us-states-density.ts
  website/offline-examples/choropleth/administrative/API.en.md
  website/offline-examples/choropleth/administrative/API.zh.md
  website/offline-examples/choropleth/administrative/demo/administrative-switch.tsx
  website/offline-examples/choropleth/administrative/demo/china-city.ts
  website/offline-examples/choropleth/administrative/demo/china-map.ts
  website/offline-examples/choropleth/administrative/demo/hangzhou-city.ts
  website/offline-examples/choropleth/administrative/demo/meta.json
  website/offline-examples/choropleth/administrative/demo/world-map.ts
  website/offline-examples/choropleth/administrative/demo/xihu-district.ts
  website/offline-examples/choropleth/administrative/demo/zhejiang-province-district.ts
  website/offline-examples/choropleth/administrative/demo/zhejiang-province.ts
  website/offline-examples/choropleth/administrative/index.en.md
  website/offline-examples/choropleth/administrative/index.zh.md
  website/offline-examples/choropleth/advanced-plot/muti-plots/API.en.md
  website/offline-examples/choropleth/advanced-plot/muti-plots/API.zh.md
  website/offline-examples/choropleth/advanced-plot/muti-plots/demo/china-bubble.ts
  website/offline-examples/choropleth/advanced-plot/muti-plots/demo/meta.json
  website/offline-examples/choropleth/advanced-plot/muti-plots/demo/world-bubble.ts
  website/offline-examples/choropleth/advanced-plot/muti-plots/index.en.md
  website/offline-examples/choropleth/advanced-plot/muti-plots/index.zh.md
  website/offline-examples/choropleth/drill/API.en.md
  website/offline-examples/choropleth/drill/API.zh.md
  website/offline-examples/choropleth/drill/demo/drill-callback.ts
  website/offline-examples/choropleth/drill/demo/drill-intercept.ts
  website/offline-examples/choropleth/drill/demo/meta.json
  website/offline-examples/choropleth/drill/demo/order-drill.ts
  website/offline-examples/choropleth/drill/demo/unorder-drill.ts
  website/offline-examples/choropleth/drill/index.en.md
  website/offline-examples/choropleth/drill/index.zh.md
Labels: documentation

#217 docs: 更新 Demo 底图
  packages/l7plot/src/core/layer/plot-layer.ts
  packages/l7plot/src/types/layer.ts
  website/examples/advanced-plot/muti-layers/demo/air-fly.ts
  website/examples/advanced-plot/muti-layers/demo/fly-flow.ts
  website/examples/advanced-plot/muti-layers/demo/wind-field.ts
  website/examples/area/division/demo/europe-pop-est.ts
  website/examples/area/division/demo/us-states-density.ts
  website/examples/area/interactive/demo/multiple-choice.ts
  website/examples/area/interactive/demo/single-choice.ts
  website/examples/dot/bobble/demo/air-temperature.ts
  website/examples/dot/bobble/demo/animate.ts
  website/examples/dot/bobble/demo/distribution-cities.ts
  website/examples/dot/bobble/demo/earthquake-level.ts
  website/examples/dot/dot-density/demo/beijing-traffic.ts
  website/examples/dot/dot-density/demo/cuisine-nationwide.ts
  website/examples/dot/dot-density/demo/shanghai-traffic.ts
  website/examples/dot/icon/demo/bank.ts
  website/examples/dot/icon/demo/poi.ts
  website/examples/dot/scatter/demo/classified-scatter.ts
  website/examples/dot/scatter/demo/distribution-cities.ts
  website/examples/flow/flow/demo/fly-flow.ts
  website/examples/flow/flow/demo/ground-flow.ts
  website/examples/gallery/distribution/demo/global-earthquake.ts
  website/examples/gallery/distribution/demo/population-gdp.ts
  website/examples/heat/grid/demo/grid2d.ts
  website/examples/heat/grid/demo/grid3d.ts
  website/examples/heat/heatmap/demo/global-2d.ts
  website/examples/heat/heatmap/demo/global-3d.ts
  website/examples/heat/heatmap/demo/housing-transaction.ts
  website/examples/heat/heatmap/demo/traffic-accident.ts
  website/examples/heat/hexbin/demo/hexbin3d.ts
  website/examples/heat/hexbin/demo/traffic-delay.ts
  website/examples/path/path/demo/beijingBusPath.ts
  website/examples/path/path/demo/beijingMetro.ts
  website/examples/path/path/demo/busLevelRoutes.ts
  website/examples/path/path/demo/trail.ts
  website/offline-examples/choropleth/administrative/demo/administrative-switch.tsx
  website/offline-examples/choropleth/administrative/demo/china-city.ts
  website/offline-examples/choropleth/administrative/demo/china-map.ts
  website/offline-examples/choropleth/administrative/demo/hangzhou-city.ts
  website/offline-examples/choropleth/administrative/demo/world-map.ts
  website/offline-examples/choropleth/administrative/demo/xihu-district.ts
  website/offline-examples/choropleth/administrative/demo/zhejiang-province-district.ts
  website/offline-examples/choropleth/administrative/demo/zhejiang-province.ts
  website/offline-examples/choropleth/advanced-plot/muti-plots/demo/china-bubble.ts
  website/offline-examples/choropleth/advanced-plot/muti-plots/demo/world-bubble.ts
  website/offline-examples/choropleth/drill/demo/drill-callback.ts
  website/offline-examples/choropleth/drill/demo/drill-intercept.ts
  website/offline-examples/choropleth/drill/demo/order-drill.ts
  website/offline-examples/choropleth/drill/demo/unorder-drill.ts
Labels: documentation

#218 docs: 修改图层事件
  packages/composite-layers/src/core/constants.ts
  packages/composite-layers/src/types/common.ts
  website/docs/api/plot-api/index.zh.md
  website/docs/common/composite-layers/composite-common/event.zh.md
  website/docs/common/composite-layers/core-common/event.zh.md
Labels: documentation

#220 feat: 新增图片图层
  packages/composite-layers/src/core-layers/image-layer/index.ts
  packages/composite-layers/src/core-layers/image-layer/types.ts
  packages/composite-layers/src/index.ts
  storybook/stories/composite-layers/core-layer/image.tsx
  storybook/stories/composite-layers/core-layer/index.stories.tsx
  storybook/stories/composite-layers/core-layer/raster.tsx
  storybook/stories/composite-layers/raster-layer/index.stories.tsx
  website/docs/api/composite-layers/image-layer.en.md
  website/docs/api/composite-layers/image-layer.zh.md
  website/docs/common/composite-layers/image-layer/source.en.md
  website/docs/common/composite-layers/image-layer/source.zh.md
  website/docs/common/composite-layers/image-layer/style.en.md
  website/docs/common/composite-layers/image-layer/style.zh.md
Labels: feature

#221 docs: 修复文档 API 归类问题
  packages/component/package.json
  packages/composite-layers/package.json
  packages/composite-layers/src/core-layers/image-layer/types.ts
  packages/composite-layers/src/core-layers/raster-layer/types.ts
  packages/composite-layers/src/index.ts
  packages/l7plot/package.json
  website/docs/api/composite-layers/bubble-layer.zh.md
  website/docs/api/composite-layers/choropleth-layer.zh.md
  website/docs/common/composite-layers/heatmap-layer/style.zh.md
Labels: documentation

#222 chore: 升级依赖
  package.json
Labels: ignore-for-release
