Repository antvis/L7Plot, pull requests merged in 2022-11, with the labels that each got.

#242 fix(map): map.once should emit only one time
  packages/l7plot/__tests__/unit/core/map/event.test.ts
  packages/l7plot/src/core/map/index.ts
Labels: bugfix

#243 fix: 修复 maxZoom 更新失败问题
  packages/composite-layers/src/core/core-layer.ts
Labels: bugfix

#244 feat: 核心图层新增 getSource 方法
  packages/composite-layers/src/composite-layers/bubble-layer/index.ts
  packages/composite-layers/src/composite-layers/choropleth-layer/index.ts
  packages/composite-layers/src/composite-layers/icon-layer/icon.ts
  packages/composite-layers/src/core/composite-layer.ts
  packages/composite-layers/src/core/core-layer.ts
  packages/composite-layers/src/types/interface.ts
  website/docs/common/composite-layers/composite-common/method.zh.md
  website/docs/common/composite-layers/core-common/method.zh.md
Labels: feature

#246 fix: 获取图层图例数据异步情况
  packages/l7plot/__tests__/unit/plots/dot/index.test.ts
  packages/l7plot/__tests__/unit/plots/heatmap/index.test.ts
  packages/l7plot/src/core/map/index.ts
Labels: bugfix

#248 feat: 地图底图支持高德V2
  packages/composite-layers/src/composite-layers/choropleth-layer/index.ts
  packages/composite-layers/src/core/composite-layer.ts
  packages/composite-layers/src/core/core-layer.ts
  packages/composite-layers/src/types/interface.ts
  packages/l7plot/__tests__/unit/adaptor/layer/index.spec.ts
  packages/l7plot/__tests__/unit/layers/column-layer/index.test.ts
  packages/l7plot/__tests__/unit/layers/dot-layer/index.test.ts
  packages/l7plot/__tests__/unit/layers/heatmap-layer/index.test.ts
  packages/l7plot/__tests__/unit/layers/icon-layer/index.test.ts
  packages/l7plot/__tests__/unit/layers/text-layer/index.test.ts
  packages/l7plot/src/component/legend.ts
  packages/l7plot/src/component/tooltip.ts
  packages/l7plot/src/core/layer/plot-layer.ts
  packages/l7plot/src/core/map/index.ts
  packages/l7plot/src/core/plot/index.ts
  packages/l7plot/src/layers/area-layer/index.ts
  packages/l7plot/src/layers/dot-layer/index.ts
  packages/l7plot/src/layers/grid-layer/index.ts
  packages/l7plot/src/layers/heatmap-layer/adaptor.ts
  packages/l7plot/src/layers/heatmap-layer/index.ts
  packages/l7plot/src/layers/hexbin-layer/index.ts
  packages/l7plot/src/layers/lines-layer/index.ts
  packages/l7plot/src/layers/prism-layer/index.ts
  packages/l7plot/src/layers/text-layer/index.ts
  packages/l7plot/src/plots/choropleth/index.ts
  packages/l7plot/src/types/attr.ts
  packages/l7plot/src/types/common.ts
  packages/l7plot/src/types/control.ts
  packages/l7plot/src/types/layer.ts
  packages/l7plot/src/types/legend.ts
  packages/l7plot/src/types/map.ts
  packages/l7plot/src/types/popup.ts
  packages/l7plot/src/types/tooltip.ts
  website/docs/api/plot-api/index.zh.md
  website/docs/common/attribute/map.zh.md
  website/docs/manual/faq/index.zh.md
Labels: feature

#249 fix: 填补图层原始事件
  packages/composite-layers/src/core/constants.ts
  packages/l7plot/package.json
  storybook/package.json
  storybook/stories/composite-layers/core-layer/index.stories.tsx
  storybook/stories/composite-layers/polygon-layer/index.stories.tsx
  storybook/stories/core-layers/ImageLayer.tsx
  storybook/stories/core-layers/L7LineLayer.tsx
  storybook/stories/core-layers/LineLayer.tsx
  storybook/stories/core-layers/PolygonLayer.tsx
  storybook/stories/core-layers/RasterLayer.tsx
  storybook/stories/core-layers/index.stories.tsx
  website/docs/common/base-layers/base-common/event.zh.md
  website/docs/common/composite-layers/composite-common/event.zh.md
Labels: bugfix

#250 feat: 复合图层多选功能
  package.json
  packages/composite-layers/package.json
  packages/composite-layers/src/composite-layers/bubble-layer/constants.ts
  packages/composite-layers/src/composite-layers/bubble-layer/index.ts
  packages/composite-layers/src/composite-layers/bubble-layer/types.ts
  packages/composite-layers/src/composite-layers/choropleth-layer/constants.ts
  packages/composite-layers/src/composite-layers/choropleth-layer/index.ts
  packages/composite-layers/src/composite-layers/choropleth-layer/types.ts
  packages/composite-layers/src/composite-layers/common/multi-select.ts
  packages/composite-layers/src/composite-layers/icon-layer/constants.ts
  packages/composite-layers/src/composite-layers/icon-layer/icon.ts
  packages/composite-layers/src/composite-layers/icon-layer/types.ts
  packages/composite-layers/src/core/composite-layer.ts
  packages/composite-layers/src/core/layer-group.ts
  packages/composite-layers/src/types/interface.ts
  packages/composite-layers/src/utils/index.ts
  packages/composite-layers/src/utils/keypress.ts
  storybook/stories/composite-layers/choropleth-layer/Select.tsx
  storybook/stories/composite-layers/choropleth-layer/index.stories.tsx
  website/docs/api/composite-layers/bubble-layer.zh.md
  website/docs/api/composite-layers/choropleth-layer.zh.md
  website/docs/api/composite-layers/icon-font-layer.zh.md
  website/docs/api/composite-layers/icon-image-layer.zh.md
  website/docs/common/base-layers/base-common/method.zh.md
  website/docs/common/composite-layers/composite-common/method.zh.md
Labels: feature

#251 fix: 修复复合图层多选触发条件
  packages/composite-layers/src/composite-layers/common/multi-select.ts
Labels: bugfix

#253 fix: icon layer image 加载时机
  packages/composite-layers/package.json
  packages/composite-layers/src/composite-layers/choropleth-layer/index.ts
  packages/composite-layers/src/composite-layers/choropleth-layer/types.ts
  packages/composite-layers/src/composite-layers/icon-layer/icon-image.ts
  packages/composite-layers/src/composite-layers/icon-layer/types.ts
  packages/l7plot/package.json
  packages/l7plot/src/layers/area-layer/adaptor.ts
  packages/l7plot/src/layers/area-layer/types.ts
  storybook/package.json
  storybook/stories/core-layers/index.stories.tsx
  storybook/stories/core-layers/rastertileLayer.tsx
  storybook/stories/plots/choropleth/WorldSufei.tsx
  website/docs/common/layers/area-layer/style.zh.md
  website/offline-examples/choropleth/administrative/demo/world-map.ts
  website/package.json
Labels: bugfix

#252 docs: 给点图层添加示例
  storybook/stories/core-layers/PointLayer.tsx
  storybook/stories/core-layers/index.stories.tsx
Labels: documentation

#254 fix: 修复复合图层批量更新问题
  README.en-US.md
  README.md
  packages/composite-layers/src/composite-layers/bubble-layer/index.ts
  packages/composite-layers/src/composite-layers/choropleth-layer/index.ts
  packages/composite-layers/src/composite-layers/icon-layer/icon.ts
  packages/composite-layers/src/core/composite-layer.ts
  packages/composite-layers/src/core/core-layer.ts
  packages/composite-layers/src/types/interface.ts
  packages/l7plot/README.md
  storybook/stories/composite-layers/bubble-layer/Earthquake.tsx
  storybook/stories/core-layers/TextLayer.tsx
  storybook/stories/core-layers/index.stories.tsx
  website/docs/api/plot-api/index.zh.md
  website/docs/common/base-layers/text-layer/style.zh.md
  website/gatsby-config.js
Labels: bugfix
