Repository antvis/L7Plot, pull requests merged in 2022-10, with the labels that each got.

#227 docs: 更新栅格图层文档
  packages/composite-layers/src/core-layers/raster-layer/types.ts
  website/docs/api/composite-layers/bubble-layer.en.md
  website/docs/api/composite-layers/bubble-layer.zh.md
  website/docs/api/composite-layers/choropleth-layer.en.md
  website/docs/api/composite-layers/choropleth-layer.zh.md
  website/docs/api/composite-layers/heatmap-layer.en.md
  website/docs/api/composite-layers/heatmap-layer.zh.md
  website/docs/api/composite-layers/image-layer.en.md
  website/docs/api/composite-layers/image-layer.zh.md
  website/docs/api/composite-layers/polygon-layer.en.md
  website/docs/api/composite-layers/polygon-layer.zh.md
  website/docs/api/composite-layers/raster-layer.en.md
  website/docs/api/composite-layers/raster-layer.zh.md
  website/docs/api/composite-layers/text-layer.en.md
  website/docs/api/composite-layers/text-layer.zh.md
  website/docs/common/composite-layers/raster-layer/source.zh.md
  website/docs/common/composite-layers/raster-layer/style.zh.md
Labels: documentation

#226 feat: 新增 IconLayer
  packages/composite-layers/src/composite-layers/bubble-layer/index.ts
  packages/composite-layers/src/composite-layers/choropleth-layer/index.ts
  packages/composite-layers/src/composite-layers/icon-layer/adaptor.ts
  packages/composite-layers/src/composite-layers/icon-layer/constants.ts
  packages/composite-layers/src/composite-layers/icon-layer/icon-font.ts
  packages/composite-layers/src/composite-layers/icon-layer/icon-image.ts
  packages/composite-layers/src/composite-layers/icon-layer/icon.ts
  packages/composite-layers/src/composite-layers/icon-layer/types.ts
  packages/composite-layers/src/core-layers/point-layer/types.ts
  packages/l7plot/__tests__/unit/core/map/register.test.ts
  storybook/stories/composite-layers/bubble-layer/Earthquake.tsx
  storybook/stories/composite-layers/icon-layer/IconFont.tsx
  storybook/stories/composite-layers/icon-layer/iconImage.tsx
  storybook/stories/plots/dot/POI.tsx
  website/docs/api/composite-layers/icon-font-layer.zh.md
  website/docs/api/composite-layers/icon-image-layer.zh.md
  website/examples/composite/iconImage/API.en.md
  website/examples/composite/iconImage/API.zh.md
  website/examples/composite/iconImage/demo/image.ts
  website/examples/composite/iconImage/demo/meta.json
  website/examples/composite/iconImage/index.en.md
  website/examples/composite/iconImage/index.zh.md
  website/examples/composite/iconfont/API.en.md
  website/examples/composite/iconfont/API.zh.md
  website/examples/composite/iconfont/demo/font.ts
  website/examples/composite/iconfont/demo/meta.json
  website/examples/composite/iconfont/index.en.md
  website/examples/composite/iconfont/index.zh.md
  website/gatsby-browser.js
  website/gatsby-config.js
Labels: feature

#231 feat: 新增复合图层获取图例方法
  packages/composite-layers/package.json
  packages/composite-layers/src/core/composite-layer.ts
  packages/composite-layers/src/core/core-layer.ts
  packages/composite-layers/src/types/common.ts
  packages/composite-layers/src/types/interface.ts
  packages/l7plot/package.json
  website/docs/common/composite-layers/composite-common/event.zh.md
  website/docs/common/composite-layers/composite-common/method.zh.md
  website/docs/common/composite-layers/core-common/event.zh.md
  website/docs/common/composite-layers/core-common/method.zh.md
Labels: feature

#233 fix: 修复图层图例事件
  packages/composite-layers/src/core/constants.ts
Labels: bugfix

#234 docs: 图标图层文档完善
  packages/composite-layers/src/composite-layers/icon-layer/types.ts
  website/docs/api/composite-layers/icon-font-layer.en.md
  website/docs/api/composite-layers/icon-font-layer.zh.md
  website/docs/api/composite-layers/icon-image-layer.en.md
  website/docs/api/composite-layers/icon-image-layer.zh.md
Labels: documentation

#235 chore: 给复合图层显隐方法类型补充
  packages/composite-layers/src/core/composite-layer.ts
  packages/composite-layers/src/core/core-layer.ts
  packages/composite-layers/src/types/interface.ts
Labels: ignore-for-release

#237 fix: 修复复合图层从场景中移除 bug
  packages/composite-layers/src/core/layer-group.ts
Labels: bugfix

#238 fix: 图层接口类型缺失
  packages/composite-layers/src/types/interface.ts
  packages/l7plot/__tests__/unit/core/plot/index.test.ts
  packages/l7plot/src/component/legend.ts
  packages/l7plot/src/core/map/index.ts
  packages/l7plot/src/types/control.ts
Labels: bugfix
