Repository antvis/L7Plot, pull requests merged in 2023-06, with the labels that each got.

#292 fix: support unit option in dot style config
  packages/l7plot/src/types/layer.ts
  website/docs/common/base-layers/point-layer/style.zh.md
  website/docs/common/layers/dot-layer/style.zh.md
Labels: bugfix

#295 feat: 新增客流聚合图层
  .gitignore
  jest.config.js
  package.json
  packages/composite-layers/__tests__/unit/composite-layers/flow-layer/index.test.ts
  packages/composite-layers/package.json
  packages/composite-layers/src/composite-layers/flow-layer/constants.ts
  packages/composite-layers/src/composite-layers/flow-layer/data/build-index.ts
  packages/composite-layers/src/composite-layers/flow-layer/data/cluster/flows.ts
  packages/composite-layers/src/composite-layers/flow-layer/data/cluster/hca.ts
  packages/composite-layers/src/composite-layers/flow-layer/data/cluster/index.ts
  packages/composite-layers/src/composite-layers/flow-layer/data/index.ts
  packages/composite-layers/src/composite-layers/flow-layer/data/transform.ts
  packages/composite-layers/src/composite-layers/flow-layer/index.ts
  packages/composite-layers/src/composite-layers/flow-layer/types/index.ts
  packages/composite-layers/src/composite-layers/flow-layer/utils/id.ts
  packages/composite-layers/src/composite-layers/flow-layer/utils/index.ts
  packages/composite-layers/src/composite-layers/flow-layer/utils/style.ts
  packages/composite-layers/src/composite-layers/flow-layer/utils/zoom.ts
  packages/composite-layers/src/core-layers/line-layer/types.ts
  packages/composite-layers/src/core-layers/point-layer/types.ts
  packages/composite-layers/src/index.ts
  packages/composite-layers/src/types/category.ts
  website/.dumi/global.ts
  website/.dumirc.ts
  website/docs/api/composite-layers/flow-layer.en.md
  website/docs/api/composite-layers/flow-layer.zh.md
  website/docs/common/base-layers/line-layer/shape.zh.md
  website/docs/common/base-layers/point-layer/style.zh.md
  website/examples/composite/trafficFlow/API.en.md
  website/examples/composite/trafficFlow/API.zh.md
  website/examples/composite/trafficFlow/demo/base.js
  website/examples/composite/trafficFlow/demo/meta.json
  website/examples/composite/trafficFlow/index.en.md
  website/examples/composite/trafficFlow/index.zh.md
  website/package.json
Labels: feature

#291 fix: emit 'drillup' event in `drillUp` function
  packages/l7plot/src/plots/choropleth/index.ts
Labels: bugfix

#289 fix: emit 'drilldown' event in `drillDown` function
  packages/l7plot/src/plots/choropleth/index.ts
Labels: bugfix

#297 docs: 修复文档中部分问题
  website/docs/api/composite-layers/flow-layer.zh.md
Labels: documentation

#298 fix: 替换 d3 系列包，以修复 umd 打包体积过大的问题
  packages/composite-layers/package.json
  packages/composite-layers/rollup.config.js
  packages/composite-layers/src/composite-layers/flow-layer/index.ts
  packages/composite-layers/src/composite-layers/flow-layer/utils/style.ts
  packages/composite-layers/src/composite-layers/flow-layer/utils/zoom.ts
  packages/l7plot/rollup.config.js
Labels: bugfix

#299 fix: 完善客流聚合图层事件能力
  .gitignore
  packages/composite-layers/src/composite-layers/flow-layer/index.ts
  packages/composite-layers/src/core/constants.ts
  website/docs/api/composite-layers/flow-layer.zh.md
  website/docs/common/base-layers/base-common/event.zh.md
  website/examples/composite/trafficFlow/demo/base.js
Labels: bugfix
